### ISSUE TITLE
Hard Coded Grafana Dashboard Datasource should be derived instead

### ISSUE THREAD

**Issue by Otterpohl** [cockroachlabs/visus#67]
The example Grafana Dashboard should use a variable which queries a list of Prometheus compatible datasources.

This way anyone that imports the dashboard can see data immediately, or they can switch to the datasource where the Visus metrics are available.

I am happy to raise a PR with an amended version.

![image](https://github.com/cockroachlabs/visus/assets/82106086/8bf3b00c-f062-4be4-8249-0c8428c4754b)

**Comment by sravotto** [comment]
@Otterpohl  feel free to open a PR with the change, the request makes sense to me. Thank you.
