### ISSUE TITLE
Support certificates rotation

### ISSUE THREAD

**Issue by ihab-soliman-form3** [cockroachlabs/visus#94]
Cockroachdb support certificate rotation on sighup, can we have the same in visus on both the http server and the db connection.
Proposed solution is to:
- Update pgxpool to v5
- Use the `Reset` function in the pool to close the connections without closing the pool
- Set the tls config on both http server and the pool config to reload the certificate 

I do have the changes ready but I can't seem to be able to push new a branch.

**Comment by sravotto** [comment]
Hi @ihab-soliman-form3,  if you'd like to submit a change for review, please fork the repo into your github account, push the change to a branch on your own fork, then open a PR to the main branch on the this repository. I'll be happy to review your changes.

**Comment by ihab-soliman-form3** [comment]
Thanks @sravotto, I am aware of that process 😄 just needed confirmation and find a way that would work with our policies

**Comment by ihab-soliman-form3** [comment]
Thanks @sravotto, I am aware of that process 😄 just needed confirmation

**Comment by ihab-soliman-form3** [comment]
@sravotto I also created this PR https://github.com/cockroachlabs/visus/pull/100
